# Global LLM configuration
[llm]
model = "doubao-1-5-ui-tars-250428"       # The LLM model to use
base_url = "https://ark.cn-beijing.volces.com/api/v3" # API endpoint URL
api_key = "a7c5e7a8-67a0-4c64-b9e4-bceba62d4e67"                   # Your API key
max_tokens = 8192                          # Maximum number of tokens in the response
temperature = 1.3                        # Controls randomness
